name: 'Deploy Nightly'
description: 'Deploy an asset to a GitHub release with date and commit hash and delete old assets.'
author: 'WebFreak001'

branding:
  icon: 'grid'
  color: 'purple'

inputs:
  upload_url:
    description: 'GitHub upload URL'
    required: true
  release_id:
    description: 'GitHub release id'
    required: true
  asset_name:
    description: 'Name of the file to upload with a $$ placeholder to insert date and hash into'
    required: true
  asset_content_type:
    description: 'Content type of the uploaded file'
    required: true

output:
  cancelled:
    description: 'yes if a new commit has been made, no if we can build'
  url:
    description: 'GitHub asset URL'

runs:
  using: 'node12'
  main: 'index.js'
